CREATE TABLE `ifdm`.`fines_treatment_selection` 
( 
	`id` INT NOT NULL AUTO_INCREMENT , 
	`quartz` FLOAT NOT NULL , 
	`microcline` FLOAT NOT NULL , 
	`orthoclase` FLOAT NOT NULL , 
	`albite` FLOAT NOT NULL , 
	`plagioClase` FLOAT NOT NULL , 
	`biotite` FLOAT NOT NULL , 
	`muscovite` FLOAT NOT NULL , 
	`chloritem` FLOAT NOT NULL , 
	`kaolinite` FLOAT NOT NULL , 
	`illite` FLOAT NOT NULL , 
	`emectite` FLOAT NOT NULL , 
	`chloritec` FLOAT NOT NULL , 
	`brucite` FLOAT NOT NULL , 
	`gibbsite` FLOAT NOT NULL ,
	`calcite` FLOAT NOT NULL , 
	`dolomite` FLOAT NOT NULL , 
	`ankeritec` FLOAT NOT NULL , 
	`sideritec` FLOAT NOT NULL , 
	`cast` FLOAT NOT NULL , 
	`anhydrite` FLOAT NOT NULL , 
	`baryte` FLOAT NOT NULL , 
	`celestine` FLOAT NOT NULL ,
	`halite` FLOAT NOT NULL , 
	`hematite` FLOAT NOT NULL , 
	`magnetite` FLOAT NOT NULL , 
	`pyrrhotite` FLOAT NOT NULL , 
	`pyrite` FLOAT NOT NULL , 
	`chloriteim` FLOAT NOT NULL , 
	`sideriteim` FLOAT NOT NULL ,
	`ankeriteim` FLOAT NOT NULL , 
	`glauconite` FLOAT NOT NULL , 
	`chamosite` FLOAT NOT NULL ,
	`troilite` FLOAT NOT NULL , 
	`stilbite` FLOAT NOT NULL , 
	`heulandite` FLOAT NOT NULL ,
	`chabazite` FLOAT NOT NULL , 
	`natrolite` FLOAT NOT NULL , 
	`analcime` FLOAT NOT NULL ,
	`melanterite` FLOAT NOT NULL , 
	`bentonite` FLOAT NOT NULL , 
	`finesna` FLOAT NOT NULL , 
	`tc` FLOAT NOT NULL , 
	`ty` FLOAT NOT NULL , 
	`h2s` FLOAT NOT NULL , 
	`iic` FLOAT NOT NULL , 
	`k` FLOAT NOT NULL , 
	`em` FLOAT NOT NULL , 
	`wet` FLOAT NOT NULL , 
	`tvd` FLOAT NOT NULL ,
	`isl` FLOAT NOT NULL , 
	`sal` FLOAT NOT NULL , 
	`escenario_id` INT NOT NULL ,
	    PRIMARY KEY (`id`), 
	    INDEX (`escenario_id`),
	    FOREIGN KEY (`escenario_id`) REFERENCES escenarios(`id`)) ENGINE = InnoDB;

UPDATE `advisor` 
SET`fines_treatment_selection`= '{"quartz":"SELECT quartz FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",       
"microcline":"SELECT microcline FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",   
"orthoclase":"SELECT orthoclase FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"albite":"SELECT albite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"plagioClase":"SELECT plagioClase FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"biotite":"SELECT biotite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"muscovite":"SELECT muscovite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"chloritem":"SELECT chloritem FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"kaolinite":"SELECT kaolinite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"illite":"SELECT illite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"emectite":"SELECT emectite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"chloritec":"SELECT chloritec FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"brucite":"SELECT brucite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"gibbsite":"SELECT gibbsite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"calcite":"SELECT calcite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"dolomite":"SELECT dolomite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"ankeritec":"SELECT ankeritec FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"sideritec":"SELECT sideritec FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"cast":"SELECT cast FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"anhydrite":"SELECT anhydrite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"baryte":"SELECT baryte FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"celestine":"SELECT celestine FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"halite":"SELECT halite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"hematite":"SELECT hematite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"magnetite":"SELECT magnetite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"pyrrhotite":"SELECT pyrrhotite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"pyrite":"SELECT pyrite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"chloriteim":"SELECT chloriteim FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"sideriteim":"SELECT sideriteim FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"ankeriteim":"SELECT ankeriteim FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"glauconite":"SELECT glauconite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"chamosite":"SELECT chamosite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"troilite":"SELECT troilite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",  
"stilbite":"SELECT stilbite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"heulandite":"SELECT heulandite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"chabazite":"SELECT chabazite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"natrolite":"SELECT natrolite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"analcime":"SELECT analcime FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"melanterite":"SELECT melanterite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"bentonite":"SELECT bentonite FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"finesna":"SELECT finesna FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1", 
"tc":"SELECT tc FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"ty":"SELECT ty FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"h2s":"SELECT h2s FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"iic":"SELECT iic FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"k":"SELECT k FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"em":"SELECT em FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"wet":"SELECT wet FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"tvd":"SELECT tvd FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"isl":"SELECT isl FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1",
"sal":"SELECT sal FROM fines_treatment_selection WHERE escenario_id = put_scenario_id ORDER BY id limit 1"}'
WHERE id = 3;